package com.jintao.vipmanager.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jintao.vipmanager.database.bean.DbConvertGoodsInfo;
import com.jintao.vipmanager.database.bean.DbUserConsumeInfo;
import com.jintao.vipmanager.database.bean.DbVipUserInfo;

import com.jintao.vipmanager.database.dao.DbConvertGoodsInfoDao;
import com.jintao.vipmanager.database.dao.DbUserConsumeInfoDao;
import com.jintao.vipmanager.database.dao.DbVipUserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbConvertGoodsInfoDaoConfig;
    private final DaoConfig dbUserConsumeInfoDaoConfig;
    private final DaoConfig dbVipUserInfoDaoConfig;

    private final DbConvertGoodsInfoDao dbConvertGoodsInfoDao;
    private final DbUserConsumeInfoDao dbUserConsumeInfoDao;
    private final DbVipUserInfoDao dbVipUserInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbConvertGoodsInfoDaoConfig = daoConfigMap.get(DbConvertGoodsInfoDao.class).clone();
        dbConvertGoodsInfoDaoConfig.initIdentityScope(type);

        dbUserConsumeInfoDaoConfig = daoConfigMap.get(DbUserConsumeInfoDao.class).clone();
        dbUserConsumeInfoDaoConfig.initIdentityScope(type);

        dbVipUserInfoDaoConfig = daoConfigMap.get(DbVipUserInfoDao.class).clone();
        dbVipUserInfoDaoConfig.initIdentityScope(type);

        dbConvertGoodsInfoDao = new DbConvertGoodsInfoDao(dbConvertGoodsInfoDaoConfig, this);
        dbUserConsumeInfoDao = new DbUserConsumeInfoDao(dbUserConsumeInfoDaoConfig, this);
        dbVipUserInfoDao = new DbVipUserInfoDao(dbVipUserInfoDaoConfig, this);

        registerDao(DbConvertGoodsInfo.class, dbConvertGoodsInfoDao);
        registerDao(DbUserConsumeInfo.class, dbUserConsumeInfoDao);
        registerDao(DbVipUserInfo.class, dbVipUserInfoDao);
    }
    
    public void clear() {
        dbConvertGoodsInfoDaoConfig.clearIdentityScope();
        dbUserConsumeInfoDaoConfig.clearIdentityScope();
        dbVipUserInfoDaoConfig.clearIdentityScope();
    }

    public DbConvertGoodsInfoDao getDbConvertGoodsInfoDao() {
        return dbConvertGoodsInfoDao;
    }

    public DbUserConsumeInfoDao getDbUserConsumeInfoDao() {
        return dbUserConsumeInfoDao;
    }

    public DbVipUserInfoDao getDbVipUserInfoDao() {
        return dbVipUserInfoDao;
    }

}
